slam_toolbox:
  ros__parameters:
    # Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    
    # Topics
    scan_topic: /scan
    
    # Mode
    mode: localization
    map_file_name: "~/ros2_dev/ros2_ws/src/turtlebot_nav_control/maps/turtlebot3_world_map.yaml"
    
    # Basic Settings
    resolution: 0.05
    max_laser_range: 5.0

    # Map and transform update intervale
    map_update_interval: 5.0
    transform_publish_period: 0.05
    
    # Minimum movement before updating map
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    
    # Scan matching - improves accuracy
    use_scan_matching: true
    
    # Loop closure - helps fix drift over time
    do_loop_closing: true
    
    # Occupancy thresholds
    occupied_thresh: 0.65   # Probability threshold to mark cell as occupied
    free_thresh: 0.196      # Probability threshold to mark cell as free